"""Add discount field to sales table

Revision ID: 6eb0e80d2778
Revises: 5d533a4554d7
Create Date: 2025-03-20 18:39:42.195827

"""
from typing import Sequence, Union
import random
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6eb0e80d2778'
down_revision: Union[str, None] = '5d533a4554d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('discount', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # fill random discount values
    discount_values = list(range(0, 51, 5))
    conn = op.get_bind()
    result = conn.execute(sa.sql.expression.text("SELECT id FROM sales"))
    sales_ids = [row[0] for row in result]
    for sale_id in sales_ids:
        random_discount = random.choice(discount_values)
        conn.execute(
            sa.sql.expression.text("UPDATE sales SET discount = :discount WHERE id = :id"),
            {"discount": random_discount, "id": sale_id}
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'discount')
    # ### end Alembic commands ###
